---
- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  tasks:
    - name: Change channel OS 7.0
      community.routeros.command:
        commands:
          - /system package update set channel=stable
          - /system package update install
          - /
      register: system_resource_print
    - name: Print its output
      ansible.builtin.debug:
        var: system_resource_print.stdout_lines
